Presentation/HPE.Kruta.Web/Controllers/CaseQueueController.cs
using HPE.Kruta.Domain;
using HPE.Kruta.Domain.Property;
using HPE.Kruta.Domain.User;
using HPE.Kruta.Model;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace HPE.Kruta.Web.Controllers
{

    public class CaseQueueController : BaseController
    {
        /// <summary>
        /// Default action. 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //Get Department name from DocumentManager and show into Drop down List which is in index
            var department = new DepartmentManager().List(false).OrderBy(a => a.DepartmentName);
            ViewBag.DepartmentsList = new SelectList(department, "DepartmentID", "DepartmentName");
            LoadAssignToList();
            return View();
        }

        /// <summary>
        /// get unprocessed queue items
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult CaseQueue_Read([DataSourceRequest]DataSourceRequest request)
        {
            PropertyCaseManager caseManager = new PropertyCaseManager();

            IQueryable<PropertyCase> queues = caseManager.List().AsQueryable();
            DataSourceResult result = queues.ToDataSourceResult(request);

            var list = JsonConvert.SerializeObject(result, Formatting.None,
                new JsonSerializerSettings()
                {
                    ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
                });

            return Content(list, "application/json");

        }

        /// <summary>
        /// assign a bulk of documents to a single employee
        /// </summary>
        /// <param name="selectedQueueIds">list of selected queues ids</param>
        /// <param name="empId">employee id to assign to</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CaseQueues_BatchAssign(List<int> selectedQueueIds, int empId)
        {
            PropertyCaseManager caseManager = new PropertyCaseManager();

            if (selectedQueueIds == null || selectedQueueIds.Count == 0 || empId == 0)
                return Json(new { Success = false }, JsonRequestBehavior.AllowGet);

            caseManager.AssignEmployeeBulk(selectedQueueIds, empId);

            return Json(new { Success = true }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public ActionResult RouteQueueAndSave(List<int> selectedQueueIds, int departmentID)
        {
            PropertyCaseManager caseManager = new PropertyCaseManager();
            if (selectedQueueIds == null || selectedQueueIds.Count == 0 || departmentID == 0)
                return Json(new { Success = false }, JsonRequestBehavior.AllowGet);

            caseManager.RouteQueueList(selectedQueueIds, departmentID);

            return Json(new { Success = true }, JsonRequestBehavior.AllowGet);

        }

        /// <summary>
        /// Load the assign to drop down list
        /// </summary>
        private void LoadAssignToList()
        {
            _userManager = new UserManager();
            var emps = _userManager.ListEmployees().OrderBy(o => o.EmployeeName);
            ViewBag.RoutingControlStaffList = new SelectList(emps, "EmployeeID", "EmployeeName");
        }
    }
}

Presentation/HPE.Kruta.Web/Controllers/DocumentQueueController.cs
using HPE.Kruta.Domain;
using HPE.Kruta.Domain.Property;
using HPE.Kruta.Domain.User;
using HPE.Kruta.Model.ViewModels;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace HPE.Kruta.Web.Controllers
{

    public class DocumentQueueController : BaseController
    {
        /// <summary>
        /// Default action. 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //Get Department name from DocumentManager and show into Drop down List which is in index
            var department = new DepartmentManager().List(false).OrderBy(a => a.DepartmentName);
            ViewBag.DepartmentsList = new SelectList(department, "DepartmentID", "DepartmentName");

            var caseTypes = new CaseTypeManager().List().OrderBy(a => a.Name);
            ViewBag.CaseTypesList = new SelectList(caseTypes, "CaseTypeID", "Name");

            LoadAssignToList();
            return View();
        }

        /// <summary>
        /// get unprocessed queue items
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult Queues_Read([DataSourceRequest]DataSourceRequest request)
        {
                _queueManager = new QueueManager();

                IQueryable<QueueWithSequence> queues = this._queueManager.ListWithSequence().AsQueryable();
                DataSourceResult result = queues.ToDataSourceResult(request);

                var list = JsonConvert.SerializeObject(result, Formatting.None,
                    new JsonSerializerSettings()
                    {
                        ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
                    });

                return Content(list, "application/json");

        }

        /// <summary>
        /// assign a bulk of documents to a single employee
        /// </summary>
        /// <param name="selectedQueueIds">list of selected queues ids</param>
        /// <param name="empId">employee id to assign to</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Queues_BatchAssign(List<int> selectedQueueIds, int empId)
        {
                _queueManager = new QueueManager();

                if (selectedQueueIds == null || selectedQueueIds.Count == 0 || empId == 0)
                    return Json(new { Success = false }, JsonRequestBehavior.AllowGet);

                this._queueManager.AssignEmployeeBulk(selectedQueueIds, empId);

                return Json(new { Success = true }, JsonRequestBehavior.AllowGet);

        }

        /// <summary>
        /// Load the assign to drop down list
        /// </summary>
        private void LoadAssignToList()
        {
            _userManager = new UserManager();
            var emps = _userManager.ListEmployees().OrderBy(o => o.EmployeeName);
            ViewBag.RoutingControlStaffList = new SelectList(emps, "EmployeeID", "EmployeeName");
        }

        /// <summary>
        /// routes a queue item and saves history
        /// </summary>
        /// <param name="selectedQueueIds"></param>
        /// <param name="departmentID"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult RouteQueueAndSave(List<int> selectedQueueIds, int departmentID)
        {

            _queueManager = new QueueManager();
            if (selectedQueueIds == null || selectedQueueIds.Count == 0 || departmentID == 0)
                return Json(new { Success = false }, JsonRequestBehavior.AllowGet);

            this._queueManager.RouteQueueList(selectedQueueIds, departmentID);

            return Json(new { Success = true }, JsonRequestBehavior.AllowGet);

        }


        /// <summary>
        /// creates a case for selected documents
        /// </summary>
        /// <param name="selectedQueueIds"></param>
        /// <param name="departmentID"></param>
        /// <param name="caseTypeID"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CreatePropertyCase(List<int> selectedQueueIds, int departmentID, int caseTypeID)
        {
            PropertyCaseManager caseManager = new PropertyCaseManager();
            caseManager.CreateCase(selectedQueueIds, departmentID, caseTypeID);

            return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
        }
    }
}

Presentation/HPE.Kruta.Web/Views/Shared/Unauthorized.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Unauthorized";
}

<h1 class="text-danger">Unauthorized.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

Presentation/HPE.Kruta.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IPTS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")



    <script>
        $(document).ajaxError(function (event, jqxhr, settings, thrownError) {
            $("html").html($(jqxhr.responseText));
        });
    </script>


</head>
<body>

    <div class="container-fluid custom-brand">
        <a href="/Home"><img src="~/Images/logo.png" class="img-responsive" alt=""></a>
        <h2>San Diego County</h2>
    </div>

    <!-- Navigation Section Start -->
    <nav class="navbar custom-navbar">

        <div class="container-fluid">

            <!-- Brand Start -->
            @*            <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("IPTS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    <a class="navbar-brand" href="/Home"><img src="~/Images/logo.png" alt=""></a>
                </div>*@
            <!-- Brand End -->
            <!-- Menu Start -->
            <ul class="nav navbar-nav">
                @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                <li><a href="/Home/Index" title="Home"><span class="glyphicon glyphicon-home"></span></a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        ARCC <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Property</a></li>
                        <li><a href="#">Legal Entity</a></li>
                        <li>@Html.ActionLink("Document Queue", "Index", "DocumentQueue")</li>
                        <li>@Html.ActionLink("Case Queue", "Index", "CaseQueue")</li>
                    </ul>
                </li>
                <li><a href="#">A&amp;C</a></li>
                <li><a href="#">TTC</a></li>
                <li><a href="#">Configuration</a></li>
            </ul>

            <!-- Login Start -->
            @Html.Partial("_LoginPartial")
            <!-- Login End -->
            <!-- Menu End -->

        </div>

        @*        <div class="container custom-block"></div>*@
    </nav>
    <!-- Navigation Section End -->

    <div class="container-fluid body-content custom-body">
        @RenderSection("sidebar", required: false)
        @RenderBody()
    </div>

    <hr />
    <footer class="navbar-fixed-bottom container-fluid text-right">
        <p>&copy; @DateTime.Now.Year - HPE - IPTS</p>
    </footer>

    @RenderSection("scripts", required: false)

</body>
</html>